/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUi;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        tfsoto.setEditable(false);
        tfbakso.setEditable(false);
        tfGudeg.setEditable(false);
        tfrawon.setEditable(false);
        tfTotal.setEditable(false);
       JOptionPane.showMessageDialog(rootPane, "selamat Datang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbsoto = new javax.swing.JCheckBox();
        cbrawon = new javax.swing.JCheckBox();
        cbbakso = new javax.swing.JCheckBox();
        cbGudeg = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        tfsoto = new javax.swing.JTextField();
        tfrawon = new javax.swing.JTextField();
        tfbakso = new javax.swing.JTextField();
        tfGudeg = new javax.swing.JTextField();
        lblhitung = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblbayar = new javax.swing.JLabel();
        tfbayar = new javax.swing.JTextField();
        btnbayar = new javax.swing.JButton();
        lblkembalian = new javax.swing.JLabel();
        tfkembalian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbsoto.setText("Soto : 5000");
        cbsoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsotoActionPerformed(evt);
            }
        });

        cbrawon.setText("Rawon : 6000");
        cbrawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrawonActionPerformed(evt);
            }
        });

        cbbakso.setText("Bakso : 4000");
        cbbakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbaksoActionPerformed(evt);
            }
        });

        cbGudeg.setText("Gudeg : 8000");
        cbGudeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGudegActionPerformed(evt);
            }
        });

        jLabel1.setText("MENU MAKANAN");

        lblhitung.setText("hitung");

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        lblbayar.setText("Bayar");

        tfbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbayarActionPerformed(evt);
            }
        });

        btnbayar.setText("Bayar");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        lblkembalian.setText("Kembalian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cbGudeg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfGudeg))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cbbakso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfbakso))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbrawon)
                                        .addComponent(cbsoto))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfsoto, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                        .addComponent(tfrawon)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblkembalian)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblbayar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnbayar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnhitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnclear))
                            .addComponent(tfTotal)
                            .addComponent(tfbayar)
                            .addComponent(tfkembalian))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblhitung)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbsoto)
                            .addComponent(tfsoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbrawon)
                            .addComponent(tfrawon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbakso)
                            .addComponent(tfbakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbGudeg)
                            .addComponent(tfGudeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhitung)
                    .addComponent(btnclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbayar)
                    .addComponent(tfbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkembalian)
                    .addComponent(tfkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbsotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsotoActionPerformed
        // TODO add your handling code here:
        if (cbsoto.isSelected() == true){
            tfsoto.setEditable(true);
        }else {
            tfsoto.setEditable(false);
            tfsoto.setText("");
        }
    }//GEN-LAST:event_cbsotoActionPerformed

    private void cbrawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrawonActionPerformed
        // TODO add your handling code here:
        if (cbrawon.isSelected() == true){
            tfrawon.setEditable(true);
        }else {
            tfrawon.setEditable(false);
            tfrawon.setText("");
        }
    }//GEN-LAST:event_cbrawonActionPerformed

    private void cbbaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbaksoActionPerformed
        // TODO add your handling code here:
        if (cbbakso.isSelected() == true){
            tfbakso.setEditable(true);
        }else {
            tfbakso.setEditable(false);
            tfbakso.setText("");
        }
    }//GEN-LAST:event_cbbaksoActionPerformed

    private void cbGudegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGudegActionPerformed
        // TODO add your handling code here:
        if (cbGudeg.isSelected() == true){
            tfGudeg.setEditable(true);
        }else {
            tfGudeg.setEditable(false);
            tfGudeg.setText("");
        }
    }//GEN-LAST:event_cbGudegActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        int hitung,Soto,Bakso,Rawon,Gudeg;
        Soto = 5000;
        Rawon = 6000;
        Bakso = 4000;
        Gudeg = 8000;
        hitung = Integer.parseInt (tfbakso.getText())*Bakso +
                Integer.parseInt (tfsoto.getText())*Soto+
                Integer.parseInt (tfGudeg.getText())*Gudeg +
                Integer.parseInt (tfrawon.getText())*Rawon ;
        tfTotal.setText(String.valueOf(hitung));
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        cbsoto.setSelected(false);
        cbbakso.setSelected(false);
        cbGudeg.setSelected(false);
        cbrawon.setSelected(false);
        tfsoto.setText("");
        tfbakso.setText("");
        tfGudeg.setText("");
        tfrawon.setText("");
        tfTotal.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here: 
       int kembalian, bayar ;
       kembalian =  Integer.parseInt(tfbayar.getText())-
               Integer.parseInt(tfTotal.getText());
       tfkembalian.setText((""+kembalian));
       if (kembalian<0){
     JOptionPane.showMessageDialog(rootPane, "Uang anda kurang silahkan kembali dan bawa uang yang cukup");
       }
       
    }//GEN-LAST:event_btnbayarActionPerformed

    private void tfbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnhitung;
    private javax.swing.JCheckBox cbGudeg;
    private javax.swing.JCheckBox cbbakso;
    private javax.swing.JCheckBox cbrawon;
    private javax.swing.JCheckBox cbsoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblbayar;
    private javax.swing.JLabel lblhitung;
    private javax.swing.JLabel lblkembalian;
    private javax.swing.JTextField tfGudeg;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfbakso;
    private javax.swing.JTextField tfbayar;
    private javax.swing.JTextField tfkembalian;
    private javax.swing.JTextField tfrawon;
    private javax.swing.JTextField tfsoto;
    // End of variables declaration//GEN-END:variables
}
